### ISSUE TITLE
[Hunt] Entity

### ISSUE THREAD

**Issue by ahnichan** [MetaAir2023/MetaRPG#10]
##Description
Entity 를 개발하였을 경우 사용하는 이슈 템플릿입니다.

---

## 필드 정의
해당 엔티티의 필드를 모두 정의합니다.  
예시)

| 정의  | 타입  |이름 |
|-----|-----|--------|
| 시퀀스 | int | sequence |
|몬스터 이름| string | name |
|몬스터 HP| int | hp |
|몬스터 공격력 | int | strikingPower |
| 보상 경험치  | int |experiencePoint |
|보상 돈  | int |money |

---

## 주요 사용할 클래스
해당 엔티티를 주로 사용할 클래스를 입력합니다.   
예시)
 - ``MonsterDB``
 - ``MonsterRepository``

---

## TODO

---
- [x]  몬스터 목록 작성 및 저장
- [x]  몬스터 목록 조회 기능 개발
- [x]  sequence를 통한 몬스터 조회 기능 개발

---

## ETC
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
