### ISSUE TITLE
[Upgrade] Application.upgradeService 개발

### ISSUE THREAD

**Issue by max0901** [MetaAir2023/MetaRPG#11]
## Description
Service 를 개발하였을 경우 사용하는 이슈 템플릿 입니다.   
### 아래 항목 중 해당하는 Service의 패키지를 선택해주세요.
- [x] Application
- [ ] Domain
---
## 주요 서비스 로직
위 Service 종류 중 Application 일 경우 주요 서비스 로직을 작성해주세요.  
domain패키지에 있는 upgradeService에서 주입 받아 안에 있는 메소드를 사용한다

## 주요 비즈니스 로직
위 Service 종류 중 Domain 일 경우 주요 서비스 로직을 작성해주세요.

예시)

1. 아이템 강화 로직
2. 현재 강화 상태 체크 로직

---

## 주요 메서드
해당 클래스의 주요 메서드를 입력합니다.   
예시)
- ``calculateUpgradeItem``    
(item `upgradeLevel` 를 매개변수로 받아 강화 성공 여부를 조회하는 메서드)
~~~
private / pulbic : pulbic
parameter : int upgradeLevel
return : upgradeLevel + 1 OR 0 
~~~

---

## TODO
- [x]  domain.upgradeService에서 Application.upgradeService에 의존성 주입하기
- [x]  Application.upgradeService에서 domain.upgradeService 안에 있는 메소드 사용하여 원하는 값 출력하기
- [ ]  할일 목록을 작성한다.

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
