### ISSUE TITLE
[Upgrade] Application.UpgradeController 개발

### ISSUE THREAD

**Issue by max0901** [MetaAir2023/MetaRPG#14]
## Description
특정 클래스의 메서드를 수정할 경우 작성하는 이슈 템플릿입니다.

### 아래 항목 중 해당하는 메서드를 수정을 선택해주세요.
- [x] Create
- [ ] Update
- [ ] Delete
---

## 주요 메서드 로직

Application.UpgradeService에서 Application.UpgradeController 의존성 주입받는 로직

예시)

1. 아이템 강화 로직
2. 현재 강화 상태 체크 로직

---

## 메서드
해당 클래스의 주요 메서드를 입력합니다.   
예시)
- ``calculateUpgradeItem``    
  (item `upgradeLevel` 를 매개변수로 받아 강화 성공 여부를 조회하는 메서드)
~~~
private / pulbic : pulbic
parameter : int upgradeLevel
return : upgradeLevel + 1 OR 0 
~~~

---

## TODO
- [x]  의존성 주입 되었는지 메서드를 사용하여 값 출력하기
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
