### ISSUE TITLE
[Hunt] Application Service

### ISSUE THREAD

**Issue by ahnichan** [MetaAir2023/MetaRPG#16]
## Description
Service 를 개발하였을 경우 사용하는 이슈 템플릿입니다.   
- [x] Application
---
## 주요 서비스 로직
위 Service 종류 중 Application 일 경우 주요 서비스 로직을 작성해주세요.  
1. 사냥 로직
2. 공격 로직
3. 보상 적용 로직

---

## 주요 메서드
해당 클래스의 주요 메서드를 입력합니다.   
예시)
- ``calculateUpgradeItem``    
(item `upgradeLevel` 를 매개변수로 받아 강화 성공 여부를 조회하는 메서드)
~~~
private / pulbic : pulbic
parameter : int upgradeLevel
return : upgradeLevel + 1 OR 0 
~~~

---

## TODO
- [x]  사냥 로직을 호출하여 사냥 기능 구현
- [x]  사용자의 입력 값에 따라 도망 기능 구현
- [x]   user와 몬스터의 현 상태 값 갱신 구현

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
