### ISSUE TITLE
[Upgrade] itemRepository 개발

### ISSUE THREAD

**Issue by jiwon11** [MetaAir2023/MetaRPG#17]
## Description
Repository 를 개발하였을 경우 사용하는 이슈 템플릿입니다.

---

## 주요 메서드
해당 클래스의 주요 메서드를 입력합니다.

- ``findAllItems()`` (모든 아이템을 조회하는 메서드)
- ``searchItemBySequence`` (item `sequence` 를 매개변수로 받아 아이템 1개를 조회하는 메서드)
- ``getItemTier`` (item `sequence` 를 매개변수로 받아 해당 아이템의 티어를 반환하는 메서드)
---

## TODO
- [x]  itemDB 클래스 구현
- [x] ItemRepository 클래스 구현
- [x] itemDB 클래스 itemRepository에 의존성 주입
- [x] ``findAllItems()`` 메서드 구현
- [x] ``searchItemBySequence`` 메서드 구현
- [x] ``getItemTier `` 메서드 구현

---

## ETC

---
* itemDB 클래스를 Spring annotation을 통해 의존성을 주입하지 않고 생성자를 통해 직접 주입하였습니다.
* itemDB 를 static 키워드를 통해 singleton 으로 구현하였습니다.
* 추후 기능 구현에 따라 메서드가 추가될 수 있습니다.
