### ISSUE TITLE
[Upgrade] Upgrade Domain Service 클래스 구현

### ISSUE THREAD

**Issue by jiwon11** [MetaAir2023/MetaRPG#19]
## Description
Service 를 개발하였을 경우 사용하는 이슈 템플릿입니다.   
### 아래 항목 중 해당하는 Service의 패키지를 선택해주세요.
- [X] Domain
---

## 주요 비즈니스 로직
위 Service 종류 중 Domain 일 경우 주요 서비스 로직을 작성해주세요.

1. 아이템 강화 로직
#### 강화 로직 알고리즘
random.nextGaussian() : 평균 0.0 표준편차 1.0의 Gauss(가우스) 분포의 double 형 난수 생성
nextGaussian() 에 수를 곱할 경우 표준편차가 바뀌고 수를 더할 경우 평균이 바뀜.
updateStochasticSeed 는 upgradeLevel(1,2,3,4 ...)과 임의의 민감도를 곱하여 계산
updateStochasticSeed 와 가우시안분포 값을 곱할 경우 (표준편차를 높임)
upgradeLevel 가 높아질수록 정규 분포 상에서 확률 밀도 함수 값이 작아져
updateStochastic 의 값이 -1~1 사이일 확률이 점점 낮아짐.

2. 현재 강화 상태 체크 로직

---

## 주요 메서드
해당 클래스의 주요 메서드를 입력합니다.   

- ``checkUpgrade``    
(item `upgradeLevel` , user `money` 를 매개변수로 받아 돈으로 강화가 가능한지 체크하는 메서드)
~~~
private / pulbic : pulbic
parameter : int money, int itemSequence
return : boolean
~~~

- ``upgradeItem``    
(item `upgradeLevel` 를 매개변수로 받아 강화 성공 여부를 조회하는 메서드)
~~~
private / pulbic : private
parameter : int upgradeLevel
return : boolean
~~~

- ``calculateUpgradeItem``    
(item `upgradeLevel` 를 매개변수로 받는 강화 로직 메서드)    
~~~
private / pulbic : pulbic
parameter : int upgradeLevel
return : upgradeLevel + 1 OR 0 
~~~

---

## TODO
- [x]  itemRepository 의존성 주입
- [x] ``checkUpgrade`` 메서드 구현
- [x] ``upgradeItem`` 메서드 구현
- [x] ``calculateUpgradeItem`` 메서드 구현
- [x] ``PropertySource annotation`` 을 통해 민감도 값 프로퍼티에서 값 호출
---

## ETC

---
* 추후 개발에 따라 메서드가 추가될 수 있습니다.
