### ISSUE TITLE
아이템 도메인 서비스 강화 로직 테스트 

### ISSUE THREAD

**Issue by jiwon11** [MetaAir2023/MetaRPG#2]
# Description
아이템 강화에 관련된 ItemDomainService 메서드 단위 테스트 진행
---
---
# TODO
- ItemDomainService class 구현
- ItemDB class 구현
- ItemRepository 구현
---
- [x] Test 클래스에서 upgradeDomainService 가 의존성이 주입되는지 확인
- [x]  사용자의 소지금과 아이템 강화 비용 비교 메서드 테스트
- [x]  강화 레벨이 높을수록 강화 성공 확률 하락 로직 테스트
- [x]  내부 강화 로직에 따라 강화 성공 및 실패 테스트

---
# ETC

* Application 클래스 구현
* ContextConfiguration 클래스 구현
* 테스트 패키지 구조 정리
