### ISSUE TITLE
[Hunt] Domain Service

### ISSUE THREAD

**Issue by ahnichan** [MetaAir2023/MetaRPG#21]
## Description
Service 를 개발하였을 경우 사용하는 이슈 템플릿입니다.   
- [x] Domain
---
## 주요 비즈니스 로직
1. 전투 로직
2. 공격 로직
3. 체력 바 로직
4. 보상 경험치 계산 로직
5. 보상 돈 계산 로직
6. 상태 값 적용 로직

---

## 주요 메서드
해당 클래스의 주요 메서드를 입력합니다.   

- ``huntSetting``    
(userHp,userSTR,monsterHp,monsterSTR 를 매개변수로 받아 전투 상태값에 현 상태 값을 적용하는 메서드)
~~~
private / public : public
parameter : int userHp,int monsterHp, int userSTR, int monsterSTR
return : void
~~~
- ``hunt``    
(전투 기능 구현 메서드)
~~~
private / public : public
parameter : int num
return : void
~~~
- ``attack``    
( user와 몬스터가 번갈아서 공격하는 기능을 구현하는 메서드)
~~~
private / public : public
parameter : 
return : void
~~~
- ``hpcalc``    
( user와 몬스터의 현재 체력 상태 백분율 계산 메서드)
~~~
private / public : public
parameter : int hp
return : void
~~~

- ``getEXP``    
( 전투 종료시 몬스터에 따른 보상 값을 유저에게 적용하는 메서드)
~~~
private / public : public
parameter : 
return : void
~~~
- ``getMoney``    
( 전투 종료시 몬스터에 따른 보상 값을 유저에게 적용하는 메서드)
~~~
private / public : public
parameter : 
return : void
~~~

---

## TODO
- [x]  사냥 기능 구현 메서드 작성
- [x]  공격 기능 구현 메서드 작성
- [x]  체력 바 기능 구현 메서드 작성
- [x] 보상 기능 구현 메서드 작성

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
