### ISSUE TITLE
[Hunt] MonsterDB 구현

### ISSUE THREAD

**Issue by ahnichan** [MetaAir2023/MetaRPG#4]
# Description

---
전반적인 몬스터 설정과 사냥 기능 개발

---
# TODO

---
- [x] 몬스터 목록 작성 및 저장
- [x] 몬스터 목록 조회 기능 개발
- [x] sequence를 통한 몬스터 조회 기능 개발
---
# ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
