### ISSUE TITLE
[Hunt] ApplicationService 및 ApplicationController

### ISSUE THREAD

**Issue by ahnichan** [MetaAir2023/MetaRPG#45]
## Description
Service 를 개발하였을 경우 사용하는 이슈 템플릿입니다.   
### 아래 항목 중 해당하는 Service의 패키지를 선택해주세요.
- [ ] Application
---
## 주요 메서드

~~~

---

## TODO
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
