### ISSUE TITLE
ApplicationItemServie에서 ApplicationItemController로 의존성 주입하기

### ISSUE THREAD

**Issue by max0901** [MetaAir2023/MetaRPG#5]
# Description

---
domainService에서 의존성을 주입받은 ApplicationItemService에서 다시 ApplicationItmeController로 의존성 주입받기

---
# TODO

---
- [ ]  ApplicationItmeController에서 domainService에 있는 매소드를 실행하여 원하는 값 출력하기
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.

---
# ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
