### ISSUE TITLE
[Hunt] HuntApplication + HuntController + View 임시 구현 및 그 외 Hunt 관련 코드 변경

### ISSUE THREAD

**Issue by madirony** [MetaAir2023/MetaRPG#50]
## Description
Service 를 개발하였을 경우 사용하는 이슈 템플릿입니다.   
### 아래 항목 중 해당하는 Service의 패키지를 선택해주세요.
- [x] Application
- [x] View
---
## 주요 서비스 로직
1. 몬스터 생성용 MonsterDTO  초기화
2. 몬스터 HP 조회
3. 전투 결과 값 반환
4. HP 게이지용 HP 퍼센트 반환
5. 몬스터 도감에서 원래의 MAX 체력 조회
6. 전투 시작 전, 유효한 전투인지 판단
7. 공격/피격 메소드 분리
8. 전투 화면 구현
---

## 주요 메서드.   
- ``initMonsterDTO``    
(`sequence` 와 field 값을 입력 받아, 밸런스 조절 후 전투할 몬스터 개체를 생성하는  메서드)
~~~
private / public : public
parameter : int sequence, int field
return : MonsterDTO
~~~
- ``hunt``    
(`huntDomainService`의 역할을 줄이기 위해 분리하였음. flag 처리를 여기서 하고, 공격/피격 판단하는 메서드)
~~~
private / public : public
parameter :boolean flag, int monsterHp, int monsterATK, int userHP, int userATK
return : (int) huntDomainService.attack(monsterHp, userATK) or huntDomainService.attack(userHP, monsterATK)
~~~
- ``checkValidBattle``    
(전투 시작 전, 유효한 전투인지 검증하는 메소드 (추후 `유저 DTO/컨트롤러`가 Merge되면 로직 수정)
~~~
private / public : public
parameter : MonsterDTO monsterDTO, int userHP, int userATK
return : true or false
~~~
- ``attackToMonster``    
(유저가 몬스터에게 공격하는 메소드)
~~~
private / public : public
parameter : MonsterDTO monsterDTO, int userATK
return : monsterDTO
~~~
- ``hitFromMonster``    
(몬스가 유저에게 공격하는 메소드(유저DTO 추가 필요(?)))
~~~
private / public : public
parameter : MonsterDTO monsterDTO, int userHP
return : afterUserHP
~~~

---

## TODO
- [x]  View에서 전투 화면을 구성한다.
- [x]  전투에 필요한 메소드를 구현
- [x]  전투용 몬스터DTO가 잘 생성되는지 확인

---

## ETC

---
* UserDTO Merge후, Hunt 파트 코드 업데이트 필요함
