### ISSUE TITLE
View 클래스 수정 - 조평훈

### ISSUE THREAD

**Issue by aicompose** [MetaAir2023/MetaRPG#54]
## Description

view에서 공격 시에 이펙트를 추가함

### 아래 항목 중 해당하는 메서드를 수정을 선택해주세요.

- [x] Update

---

## 주요 메서드 로직
AttackEffect 로직 - 공격 시에 공격 effect를 추가하였다.

## 메서드

---

## TODO
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
