### ISSUE TITLE
[Hunt] good hunter

### ISSUE THREAD

**Issue by ahnichan** [MetaAir2023/MetaRPG#61]
## Description
특정 클래스의 메서드를 수정할 경우 작성하는 이슈 템플릿입니다.

### 아래 항목 중 해당하는 메서드를 수정을 선택해주세요.

- [x] Update

---

1. 돈 보상 계산 로직
2.  huntDTO를 통한 체력 계산
3. huntDTO를 통한 공격력 계산

---

## TODO
- [x]  할일 목록을 작성한다.
- [x]  할일 목록을 작성한다.
- [x]  할일 목록을 작성한다.

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
