### ISSUE TITLE
[Hunt] domain Service

### ISSUE THREAD

**Issue by ahnichan** [MetaAir2023/MetaRPG#7]
# Description

---
이슈 내용에 대해 간단히 설명한다.

---
# TODO

---
- [ ]  user와 몬스터의 상태 값 주입
- [ ] 몬스터 공격 기능 구현
- [ ] user와 몬스터 체력 바 구현
- [ ] 경험치 및 돈 보상 구현
- [ ] 사냥 기능 구현
- [ ] 사냥 실패 시 메인으로 돌아가기

---
# ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
