### ISSUE TITLE
view에서 많은 책임을 지는 메소드 분리

### ISSUE THREAD

**Issue by aicompose** [MetaAir2023/MetaRPG#70]
## Description
특정 클래스의 메서드를 수정할 경우 작성하는 이슈 템플릿입니다.

### 아래 항목 중 해당하는 메서드를 수정을 선택해주세요.
- [ ] huntRun() 메소드에서 Tread AttackEffect 객체 생성을 huntRun 밖으로 빼내어 수정에 용이하게 만듦
---

## 주요 메서드 로직

* attackEffectUser
* attackEffectMonster 

---

## 메서드
해당 클래스의 주요 메서드를 입력합니다.   
예시)
- ``calculateUpgradeItem``    
  (item `upgradeLevel` 를 매개변수로 받아 강화 성공 여부를 조회하는 메서드)
~~~
private / pulbic : pulbic
parameter : int upgradeLevel
return : upgradeLevel + 1 OR 0 
~~~

---

## TODO
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
